### ISSUE TITLE
Unable to select sources for any zones

### ISSUE THREAD

**Issue by bimmbo** [akropp/savantaudio-homeassistant#1]
After install SavantAudio by copying to custom entities and completing setup thru the dashboard, I am able to setup the SavantAudio plugin and it generates zone devices but never sources.  There is never a menu for any of the zones to select a source.  It appears from the Savant matrix that log that it is being polled and giving a status response.

I am willing to provide any troubleshooting feedback needed.

Run on RPi4 (also from docker on NAS, same results)
Homeassistant  core version: 2024.1.2
HA Supervisor: 2023.12.0
HA OS: 11.3
Frontend: 20240104.0
SavantAudio version: 1.0.1
Savant Audio Switch Model: SSA-3220

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:894
First occurred: January 8, 2024 at 8:37:28 PM (207 occurrences)
Last logged: 12:55:30 PM

Update for media_player.savant_zone_6 fails
Update for media_player.savant_zone_7 fails
Update for media_player.savant_zone_8 fails
Update for media_player.savant_zone_17 fails
Update for media_player.savant_zone_18 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/savantaudio/client.py", line 72, in send
    await self._writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 377, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 894, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1212, in async_device_update
    await self.async_update()
  File "/config/custom_components/savantaudio/media_player.py", line 353, in async_update
    await self._output.refresh()
  File "/usr/local/lib/python3.11/site-packages/savantaudio/client.py", line 227, in refresh
    await self._switch.send_command(f'aoutput-vol-get{self._number}')
  File "/usr/local/lib/python3.11/site-packages/savantaudio/client.py", line 321, in send_command
    async for reply in self._connection.send(command):
  File "/usr/local/lib/python3.11/site-packages/savantaudio/client.py", line 52, in _close
    await self._writer.wait_closed()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 349, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1051, in write
    n = self._sock.send(data)
        ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

**Comment by akropp** [comment]
Hi, sorry!  This had been up for a while with no downloads, so I didn't really expect to be checking on issues.  Happy to take a look if you still have the issue and are trying to use it.  I think there's been a couple of updates since then (compatibility issues, mostly), but I have the same savant switch, so I can try to re-create your issue.
